# Generated by Django 4.1 on 2025-01-04 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_management", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="News",
        ),
        migrations.AlterModelManagers(
            name="customuser",
            managers=[],
        ),
    ]
