# Generated by Django 4.1 on 2025-01-07 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "user_management",
            "0003_news_alter_customuser_managers_teammember_created_at",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teammember",
            name="created_at",
        ),
    ]
