# Generated by Django 4.1 on 2025-01-07 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_management", "0004_remove_teammember_created_at"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customuser",
            managers=[],
        ),
    ]
