# Generated by Django 4.1 on 2025-01-07 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_management", "0006_alter_customuser_managers_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customuser",
            managers=[],
        ),
    ]
