# Generated by Django 4.1 on 2025-01-07 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_management", "0007_alter_customuser_managers"),
    ]

    operations = []
