# Generated by Django 4.1 on 2024-12-24 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Progress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("partner", models.IntegerField(default=0)),
                ("employee", models.IntegerField(default=0)),
                ("client", models.IntegerField(default=0)),
                ("job", models.IntegerField(default=0)),
            ],
        ),
    ]
