# Generated by Django 4.1 on 2024-12-30 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0002_progress"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Progress",
        ),
    ]
